### ISSUE TITLE
incorrect package.json location for additional native module

### ISSUE THREAD

**Issue by yuta2k** [electron-react-boilerplate/site#151]
The `package.json` for additional module definitions was moved `./app` dir to `./src ` dir in v2.0.0.
But on following page, it still says `./app`.

### Problem page
```
docs/adding-dependencies.md
```
and
https://electron-react-boilerplate.js.org/docs/adding-dependencies/

### Pull request on the boiler plate side
https://github.com/electron-react-boilerplate/electron-react-boilerplate/pull/2661

**Comment by amilajack** [comment]
fixed
