### ISSUE TITLE
add docs for auto updates

### ISSUE THREAD

**Issue by amilajack** [electron-react-boilerplate/site#2]
## Auto Updates
...todo

## Code Signing
* https://felixrieseberg.com/codesigning-electron-apps-in-ci/
* https://github.com/electron/electron-osx-sign/wiki/1.-Getting-Started#certificates

**Comment by sb-bilal-dev** [comment]
I'm really struggling with auto updates :/. I hope section for auto-updates will be added soon.

**Comment by jcyrss** [comment]
+1
