### ISSUE TITLE
Use proselint to lint grammar

### ISSUE THREAD

**Issue by vikr01** [electron-react-boilerplate/site#31]
[Proselint](https://github.com/amperser/proselint) lints grammar.

It's a python package, so it's not easy to add it as a dependency. We don't really need it as a dependency anyway, it's just something useful to add to CI.

[Webpack's site](https://github.com/webpack/webpack.js.org/blob/master/.travis.yml#L11) uses it.

**Comment by amilajack** [comment]
Awesome. Let's add it!
